---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: opa-example-app-admin
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opa-example-app-admin-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-admin
    namespace: opa-example-app-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opa-example-app-admin
