apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: opa-example-app-trigger
spec:
  serviceAccountName: tekton-triggers-admin
  bindings:
    - ref: opa-example-app-triggerbinding
  template:
    # In newer trigger versions the 'name' field will be deprecated and is
    # replaced by 'ref' field.
    ref: opa-example-app-triggertemplate
