apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: create-ingress-run
  namespace: opa-example-app-trigger
spec:
  taskRef:
    name: create-ingress
  params:
  - name: CreateCertificate
    value: "true"
  - name: CertificateKeyPassphrase
    value: asecretphrase
  - name: CertificateSecretName
    value: ingresssecret
  - name: ExternalDomain
    value: tekton-trigger.ifontlabs.com
  - name: Service
    value: el-opa-example-app-eventlistener
  - name: ServicePort
    value: "8080"
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
